version: '3.4'

services:
  fn:
    image: fnproject/fnserver:0.3.340
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 400M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:fn.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    privileged: true
    volumes:
     - ./data:/app/data
     - /var/run/docker.sock:/var/run/docker.sock

  fn-ui:
    image: fnproject/ui:0.0.26
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=4000
        - traefik.frontend.rule=Host:fn-ui.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    depends_on:
      - fn
    environment:
      - FN_API_URL=http://fn:8080

networks:
  default:
    external:
      name: traefik-net
